---
- name: Create app directory
  file:
    path: $HOME/web
    state: directory

- name: "Copy files to server"
  ansible.builtin.copy:
    src: "files/artifact.tar.gz"
    dest: "$HOME/artifact.tar.gz"
    follow: yes

- name: "install dependencies."
  become: yes
  apt:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: "Install Dependencies"
  become: yes
  shell: |
    tar -xvf artifact.tar.gz .
    rm artifact.tar.gz
    npm install

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Start Server"
  become: yes
  shell: |
    sudo pm2 stop default
    sudo pm2 start npm -- run start